"""empty message

Revision ID: 46613040f586
Revises: 170405ff7bb6
Create Date: 2025-03-11 22:50:58.938803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46613040f586'
down_revision = '170405ff7bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_num', sa.Integer(), autoincrement=True, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('tournament_num')

    # ### end Alembic commands ###
